// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proto/metrics.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ClientProfile contains static information that rarely changes
// Only sent when changed or on first connect
type ClientProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`                       // Protocol version (e.g., "2.0")
	Uuid          string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`                             // Client UUID
	CpuName       string                 `protobuf:"bytes,3,opt,name=cpu_name,json=cpuName,proto3" json:"cpu_name,omitempty"`        // e.g., "Intel Core i9-9900K"
	CpuCores      int32                  `protobuf:"varint,4,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`    // Number of CPU cores
	CpuArch       string                 `protobuf:"bytes,5,opt,name=cpu_arch,json=cpuArch,proto3" json:"cpu_arch,omitempty"`        // e.g., "x86_64"
	RamTotal      int64                  `protobuf:"varint,6,opt,name=ram_total,json=ramTotal,proto3" json:"ram_total,omitempty"`    // Total RAM in bytes
	SwapTotal     int64                  `protobuf:"varint,7,opt,name=swap_total,json=swapTotal,proto3" json:"swap_total,omitempty"` // Total swap in bytes
	DiskTotal     int64                  `protobuf:"varint,8,opt,name=disk_total,json=diskTotal,proto3" json:"disk_total,omitempty"` // Total disk space in bytes
	DiskPath      string                 `protobuf:"bytes,9,opt,name=disk_path,json=diskPath,proto3" json:"disk_path,omitempty"`     // Disk mount path (e.g., "/")
	Gpu           []*GPUProfile          `protobuf:"bytes,10,rep,name=gpu,proto3" json:"gpu,omitempty"`                              // GPU static information
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientProfile) Reset() {
	*x = ClientProfile{}
	mi := &file_proto_metrics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientProfile) ProtoMessage() {}

func (x *ClientProfile) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metrics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientProfile.ProtoReflect.Descriptor instead.
func (*ClientProfile) Descriptor() ([]byte, []int) {
	return file_proto_metrics_proto_rawDescGZIP(), []int{0}
}

func (x *ClientProfile) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ClientProfile) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *ClientProfile) GetCpuName() string {
	if x != nil {
		return x.CpuName
	}
	return ""
}

func (x *ClientProfile) GetCpuCores() int32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *ClientProfile) GetCpuArch() string {
	if x != nil {
		return x.CpuArch
	}
	return ""
}

func (x *ClientProfile) GetRamTotal() int64 {
	if x != nil {
		return x.RamTotal
	}
	return 0
}

func (x *ClientProfile) GetSwapTotal() int64 {
	if x != nil {
		return x.SwapTotal
	}
	return 0
}

func (x *ClientProfile) GetDiskTotal() int64 {
	if x != nil {
		return x.DiskTotal
	}
	return 0
}

func (x *ClientProfile) GetDiskPath() string {
	if x != nil {
		return x.DiskPath
	}
	return ""
}

func (x *ClientProfile) GetGpu() []*GPUProfile {
	if x != nil {
		return x.Gpu
	}
	return nil
}

// GPUProfile contains static GPU information
type GPUProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`                                // GPU index
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                   // GPU model name (e.g., "NVIDIA RTX 3090")
	MemoryTotal   int64                  `protobuf:"varint,3,opt,name=memory_total,json=memoryTotal,proto3" json:"memory_total,omitempty"` // Total GPU memory in bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GPUProfile) Reset() {
	*x = GPUProfile{}
	mi := &file_proto_metrics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GPUProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPUProfile) ProtoMessage() {}

func (x *GPUProfile) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metrics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPUProfile.ProtoReflect.Descriptor instead.
func (*GPUProfile) Descriptor() ([]byte, []int) {
	return file_proto_metrics_proto_rawDescGZIP(), []int{1}
}

func (x *GPUProfile) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *GPUProfile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GPUProfile) GetMemoryTotal() int64 {
	if x != nil {
		return x.MemoryTotal
	}
	return 0
}

// MetricsReport contains dynamic metrics reported every 5 seconds
// This is the main data structure for regular monitoring
type MetricsReport struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Version   string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`      // Protocol version (e.g., "2.0")
	Uuid      string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`            // Client UUID
	Timestamp int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Unix timestamp in seconds
	// CPU metrics
	CpuUsage float32 `protobuf:"fixed32,4,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"` // CPU usage percentage (0-100)
	// Memory metrics
	RamUsed  int64 `protobuf:"varint,5,opt,name=ram_used,json=ramUsed,proto3" json:"ram_used,omitempty"`    // Used RAM in bytes
	SwapUsed int64 `protobuf:"varint,6,opt,name=swap_used,json=swapUsed,proto3" json:"swap_used,omitempty"` // Used swap in bytes
	// Load average
	Load1  float32 `protobuf:"fixed32,7,opt,name=load1,proto3" json:"load1,omitempty"`   // 1-minute load average
	Load5  float32 `protobuf:"fixed32,8,opt,name=load5,proto3" json:"load5,omitempty"`   // 5-minute load average
	Load15 float32 `protobuf:"fixed32,9,opt,name=load15,proto3" json:"load15,omitempty"` // 15-minute load average
	// Disk metrics
	DiskUsed    int64 `protobuf:"varint,10,opt,name=disk_used,json=diskUsed,proto3" json:"disk_used,omitempty"`            // Used disk space in bytes
	DiskIoRead  int64 `protobuf:"varint,11,opt,name=disk_io_read,json=diskIoRead,proto3" json:"disk_io_read,omitempty"`    // Disk read bytes (delta since last report)
	DiskIoWrite int64 `protobuf:"varint,12,opt,name=disk_io_write,json=diskIoWrite,proto3" json:"disk_io_write,omitempty"` // Disk write bytes (delta since last report)
	// Network metrics
	NetInSpeed  int64 `protobuf:"varint,13,opt,name=net_in_speed,json=netInSpeed,proto3" json:"net_in_speed,omitempty"`    // Incoming network speed (bytes/sec)
	NetOutSpeed int64 `protobuf:"varint,14,opt,name=net_out_speed,json=netOutSpeed,proto3" json:"net_out_speed,omitempty"` // Outgoing network speed (bytes/sec)
	NetTotalIn  int64 `protobuf:"varint,15,opt,name=net_total_in,json=netTotalIn,proto3" json:"net_total_in,omitempty"`    // Total incoming bytes
	NetTotalOut int64 `protobuf:"varint,16,opt,name=net_total_out,json=netTotalOut,proto3" json:"net_total_out,omitempty"` // Total outgoing bytes
	// Process and connection metrics
	ProcessCount   int32 `protobuf:"varint,17,opt,name=process_count,json=processCount,proto3" json:"process_count,omitempty"`       // Number of running processes
	TcpConnections int32 `protobuf:"varint,18,opt,name=tcp_connections,json=tcpConnections,proto3" json:"tcp_connections,omitempty"` // Number of TCP connections
	UdpConnections int32 `protobuf:"varint,19,opt,name=udp_connections,json=udpConnections,proto3" json:"udp_connections,omitempty"` // Number of UDP connections
	// System uptime
	Uptime int64 `protobuf:"varint,20,opt,name=uptime,proto3" json:"uptime,omitempty"` // System uptime in seconds
	// GPU metrics (dynamic)
	Gpu []*GPUMetrics `protobuf:"bytes,21,rep,name=gpu,proto3" json:"gpu,omitempty"` // GPU dynamic metrics
	// Optional message
	Message       string `protobuf:"bytes,22,opt,name=message,proto3" json:"message,omitempty"` // Optional status message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsReport) Reset() {
	*x = MetricsReport{}
	mi := &file_proto_metrics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsReport) ProtoMessage() {}

func (x *MetricsReport) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metrics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsReport.ProtoReflect.Descriptor instead.
func (*MetricsReport) Descriptor() ([]byte, []int) {
	return file_proto_metrics_proto_rawDescGZIP(), []int{2}
}

func (x *MetricsReport) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *MetricsReport) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *MetricsReport) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *MetricsReport) GetCpuUsage() float32 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *MetricsReport) GetRamUsed() int64 {
	if x != nil {
		return x.RamUsed
	}
	return 0
}

func (x *MetricsReport) GetSwapUsed() int64 {
	if x != nil {
		return x.SwapUsed
	}
	return 0
}

func (x *MetricsReport) GetLoad1() float32 {
	if x != nil {
		return x.Load1
	}
	return 0
}

func (x *MetricsReport) GetLoad5() float32 {
	if x != nil {
		return x.Load5
	}
	return 0
}

func (x *MetricsReport) GetLoad15() float32 {
	if x != nil {
		return x.Load15
	}
	return 0
}

func (x *MetricsReport) GetDiskUsed() int64 {
	if x != nil {
		return x.DiskUsed
	}
	return 0
}

func (x *MetricsReport) GetDiskIoRead() int64 {
	if x != nil {
		return x.DiskIoRead
	}
	return 0
}

func (x *MetricsReport) GetDiskIoWrite() int64 {
	if x != nil {
		return x.DiskIoWrite
	}
	return 0
}

func (x *MetricsReport) GetNetInSpeed() int64 {
	if x != nil {
		return x.NetInSpeed
	}
	return 0
}

func (x *MetricsReport) GetNetOutSpeed() int64 {
	if x != nil {
		return x.NetOutSpeed
	}
	return 0
}

func (x *MetricsReport) GetNetTotalIn() int64 {
	if x != nil {
		return x.NetTotalIn
	}
	return 0
}

func (x *MetricsReport) GetNetTotalOut() int64 {
	if x != nil {
		return x.NetTotalOut
	}
	return 0
}

func (x *MetricsReport) GetProcessCount() int32 {
	if x != nil {
		return x.ProcessCount
	}
	return 0
}

func (x *MetricsReport) GetTcpConnections() int32 {
	if x != nil {
		return x.TcpConnections
	}
	return 0
}

func (x *MetricsReport) GetUdpConnections() int32 {
	if x != nil {
		return x.UdpConnections
	}
	return 0
}

func (x *MetricsReport) GetUptime() int64 {
	if x != nil {
		return x.Uptime
	}
	return 0
}

func (x *MetricsReport) GetGpu() []*GPUMetrics {
	if x != nil {
		return x.Gpu
	}
	return nil
}

func (x *MetricsReport) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// GPUMetrics contains dynamic GPU metrics
type GPUMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`                             // GPU index
	Utilization   float32                `protobuf:"fixed32,2,opt,name=utilization,proto3" json:"utilization,omitempty"`                // GPU utilization percentage (0-100)
	MemoryUsed    int64                  `protobuf:"varint,3,opt,name=memory_used,json=memoryUsed,proto3" json:"memory_used,omitempty"` // Used GPU memory in bytes
	Temperature   int32                  `protobuf:"varint,4,opt,name=temperature,proto3" json:"temperature,omitempty"`                 // GPU temperature in Celsius
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GPUMetrics) Reset() {
	*x = GPUMetrics{}
	mi := &file_proto_metrics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GPUMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPUMetrics) ProtoMessage() {}

func (x *GPUMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metrics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPUMetrics.ProtoReflect.Descriptor instead.
func (*GPUMetrics) Descriptor() ([]byte, []int) {
	return file_proto_metrics_proto_rawDescGZIP(), []int{3}
}

func (x *GPUMetrics) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *GPUMetrics) GetUtilization() float32 {
	if x != nil {
		return x.Utilization
	}
	return 0
}

func (x *GPUMetrics) GetMemoryUsed() int64 {
	if x != nil {
		return x.MemoryUsed
	}
	return 0
}

func (x *GPUMetrics) GetTemperature() int32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

// ProfileUpdateRequest is sent when client wants to update its static profile
type ProfileUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *ClientProfile         `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileUpdateRequest) Reset() {
	*x = ProfileUpdateRequest{}
	mi := &file_proto_metrics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileUpdateRequest) ProtoMessage() {}

func (x *ProfileUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metrics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileUpdateRequest.ProtoReflect.Descriptor instead.
func (*ProfileUpdateRequest) Descriptor() ([]byte, []int) {
	return file_proto_metrics_proto_rawDescGZIP(), []int{4}
}

func (x *ProfileUpdateRequest) GetProfile() *ClientProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

// ProfileUpdateResponse confirms profile update
type ProfileUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileUpdateResponse) Reset() {
	*x = ProfileUpdateResponse{}
	mi := &file_proto_metrics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileUpdateResponse) ProtoMessage() {}

func (x *ProfileUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metrics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileUpdateResponse.ProtoReflect.Descriptor instead.
func (*ProfileUpdateResponse) Descriptor() ([]byte, []int) {
	return file_proto_metrics_proto_rawDescGZIP(), []int{5}
}

func (x *ProfileUpdateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ProfileUpdateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// MetricsUploadRequest wraps metrics report for upload
type MetricsUploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       *MetricsReport         `protobuf:"bytes,1,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsUploadRequest) Reset() {
	*x = MetricsUploadRequest{}
	mi := &file_proto_metrics_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsUploadRequest) ProtoMessage() {}

func (x *MetricsUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metrics_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsUploadRequest.ProtoReflect.Descriptor instead.
func (*MetricsUploadRequest) Descriptor() ([]byte, []int) {
	return file_proto_metrics_proto_rawDescGZIP(), []int{6}
}

func (x *MetricsUploadRequest) GetMetrics() *MetricsReport {
	if x != nil {
		return x.Metrics
	}
	return nil
}

// MetricsUploadResponse confirms metrics receipt
type MetricsUploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsUploadResponse) Reset() {
	*x = MetricsUploadResponse{}
	mi := &file_proto_metrics_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsUploadResponse) ProtoMessage() {}

func (x *MetricsUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metrics_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsUploadResponse.ProtoReflect.Descriptor instead.
func (*MetricsUploadResponse) Descriptor() ([]byte, []int) {
	return file_proto_metrics_proto_rawDescGZIP(), []int{7}
}

func (x *MetricsUploadResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MetricsUploadResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// PingResult for ping task results
type PingResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`                          // Protocol version
	TaskId        uint32                 `protobuf:"varint,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`             // Ping task ID
	Value         int32                  `protobuf:"varint,3,opt,name=value,proto3" json:"value,omitempty"`                             // Ping result (latency in ms, or -1 for failure)
	PingType      string                 `protobuf:"bytes,4,opt,name=ping_type,json=pingType,proto3" json:"ping_type,omitempty"`        // "icmp", "tcp", or "http"
	FinishedAt    int64                  `protobuf:"varint,5,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"` // Unix timestamp when ping finished
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResult) Reset() {
	*x = PingResult{}
	mi := &file_proto_metrics_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResult) ProtoMessage() {}

func (x *PingResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metrics_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResult.ProtoReflect.Descriptor instead.
func (*PingResult) Descriptor() ([]byte, []int) {
	return file_proto_metrics_proto_rawDescGZIP(), []int{8}
}

func (x *PingResult) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PingResult) GetTaskId() uint32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *PingResult) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *PingResult) GetPingType() string {
	if x != nil {
		return x.PingType
	}
	return ""
}

func (x *PingResult) GetFinishedAt() int64 {
	if x != nil {
		return x.FinishedAt
	}
	return 0
}

var File_proto_metrics_proto protoreflect.FileDescriptor

const file_proto_metrics_proto_rawDesc = "" +
	"\n" +
	"\x13proto/metrics.proto\x12\fkomari.proto\"\xb4\x02\n" +
	"\rClientProfile\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12\x19\n" +
	"\bcpu_name\x18\x03 \x01(\tR\acpuName\x12\x1b\n" +
	"\tcpu_cores\x18\x04 \x01(\x05R\bcpuCores\x12\x19\n" +
	"\bcpu_arch\x18\x05 \x01(\tR\acpuArch\x12\x1b\n" +
	"\tram_total\x18\x06 \x01(\x03R\bramTotal\x12\x1d\n" +
	"\n" +
	"swap_total\x18\a \x01(\x03R\tswapTotal\x12\x1d\n" +
	"\n" +
	"disk_total\x18\b \x01(\x03R\tdiskTotal\x12\x1b\n" +
	"\tdisk_path\x18\t \x01(\tR\bdiskPath\x12*\n" +
	"\x03gpu\x18\n" +
	" \x03(\v2\x18.komari.proto.GPUProfileR\x03gpu\"Y\n" +
	"\n" +
	"GPUProfile\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\fmemory_total\x18\x03 \x01(\x03R\vmemoryTotal\"\xb8\x05\n" +
	"\rMetricsReport\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x1b\n" +
	"\tcpu_usage\x18\x04 \x01(\x02R\bcpuUsage\x12\x19\n" +
	"\bram_used\x18\x05 \x01(\x03R\aramUsed\x12\x1b\n" +
	"\tswap_used\x18\x06 \x01(\x03R\bswapUsed\x12\x14\n" +
	"\x05load1\x18\a \x01(\x02R\x05load1\x12\x14\n" +
	"\x05load5\x18\b \x01(\x02R\x05load5\x12\x16\n" +
	"\x06load15\x18\t \x01(\x02R\x06load15\x12\x1b\n" +
	"\tdisk_used\x18\n" +
	" \x01(\x03R\bdiskUsed\x12 \n" +
	"\fdisk_io_read\x18\v \x01(\x03R\n" +
	"diskIoRead\x12\"\n" +
	"\rdisk_io_write\x18\f \x01(\x03R\vdiskIoWrite\x12 \n" +
	"\fnet_in_speed\x18\r \x01(\x03R\n" +
	"netInSpeed\x12\"\n" +
	"\rnet_out_speed\x18\x0e \x01(\x03R\vnetOutSpeed\x12 \n" +
	"\fnet_total_in\x18\x0f \x01(\x03R\n" +
	"netTotalIn\x12\"\n" +
	"\rnet_total_out\x18\x10 \x01(\x03R\vnetTotalOut\x12#\n" +
	"\rprocess_count\x18\x11 \x01(\x05R\fprocessCount\x12'\n" +
	"\x0ftcp_connections\x18\x12 \x01(\x05R\x0etcpConnections\x12'\n" +
	"\x0fudp_connections\x18\x13 \x01(\x05R\x0eudpConnections\x12\x16\n" +
	"\x06uptime\x18\x14 \x01(\x03R\x06uptime\x12*\n" +
	"\x03gpu\x18\x15 \x03(\v2\x18.komari.proto.GPUMetricsR\x03gpu\x12\x18\n" +
	"\amessage\x18\x16 \x01(\tR\amessage\"\x87\x01\n" +
	"\n" +
	"GPUMetrics\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12 \n" +
	"\vutilization\x18\x02 \x01(\x02R\vutilization\x12\x1f\n" +
	"\vmemory_used\x18\x03 \x01(\x03R\n" +
	"memoryUsed\x12 \n" +
	"\vtemperature\x18\x04 \x01(\x05R\vtemperature\"M\n" +
	"\x14ProfileUpdateRequest\x125\n" +
	"\aprofile\x18\x01 \x01(\v2\x1b.komari.proto.ClientProfileR\aprofile\"K\n" +
	"\x15ProfileUpdateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"M\n" +
	"\x14MetricsUploadRequest\x125\n" +
	"\ametrics\x18\x01 \x01(\v2\x1b.komari.proto.MetricsReportR\ametrics\"K\n" +
	"\x15MetricsUploadResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x93\x01\n" +
	"\n" +
	"PingResult\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\rR\x06taskId\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x05R\x05value\x12\x1b\n" +
	"\tping_type\x18\x04 \x01(\tR\bpingType\x12\x1f\n" +
	"\vfinished_at\x18\x05 \x01(\x03R\n" +
	"finishedAtB.Z,github.com/komari-monitor/komari/proto;protob\x06proto3"

var (
	file_proto_metrics_proto_rawDescOnce sync.Once
	file_proto_metrics_proto_rawDescData []byte
)

func file_proto_metrics_proto_rawDescGZIP() []byte {
	file_proto_metrics_proto_rawDescOnce.Do(func() {
		file_proto_metrics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_metrics_proto_rawDesc), len(file_proto_metrics_proto_rawDesc)))
	})
	return file_proto_metrics_proto_rawDescData
}

var file_proto_metrics_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_metrics_proto_goTypes = []any{
	(*ClientProfile)(nil),         // 0: komari.proto.ClientProfile
	(*GPUProfile)(nil),            // 1: komari.proto.GPUProfile
	(*MetricsReport)(nil),         // 2: komari.proto.MetricsReport
	(*GPUMetrics)(nil),            // 3: komari.proto.GPUMetrics
	(*ProfileUpdateRequest)(nil),  // 4: komari.proto.ProfileUpdateRequest
	(*ProfileUpdateResponse)(nil), // 5: komari.proto.ProfileUpdateResponse
	(*MetricsUploadRequest)(nil),  // 6: komari.proto.MetricsUploadRequest
	(*MetricsUploadResponse)(nil), // 7: komari.proto.MetricsUploadResponse
	(*PingResult)(nil),            // 8: komari.proto.PingResult
}
var file_proto_metrics_proto_depIdxs = []int32{
	1, // 0: komari.proto.ClientProfile.gpu:type_name -> komari.proto.GPUProfile
	3, // 1: komari.proto.MetricsReport.gpu:type_name -> komari.proto.GPUMetrics
	0, // 2: komari.proto.ProfileUpdateRequest.profile:type_name -> komari.proto.ClientProfile
	2, // 3: komari.proto.MetricsUploadRequest.metrics:type_name -> komari.proto.MetricsReport
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_metrics_proto_init() }
func file_proto_metrics_proto_init() {
	if File_proto_metrics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_metrics_proto_rawDesc), len(file_proto_metrics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_metrics_proto_goTypes,
		DependencyIndexes: file_proto_metrics_proto_depIdxs,
		MessageInfos:      file_proto_metrics_proto_msgTypes,
	}.Build()
	File_proto_metrics_proto = out.File
	file_proto_metrics_proto_goTypes = nil
	file_proto_metrics_proto_depIdxs = nil
}
